const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '..');

function read(file) {
  return fs.readFileSync(path.join(repoRoot, file), 'utf8');
}

test('documentation reflects second-phase runtime structure and boundaries', () => {
  const readme = read('README.md');
  const directoryMap = read('docs/11-directory-map.md');
  const phaseTwo = read('docs/19-phase-two-status.md');
  const principles = read('docs/10-architecture-principles.md');
  const runtimeArchitecture = read('docs/01-runtime-architecture.md');
  const restApi = read('docs/21-rest-api-reference.md');
  const websocketApi = read('docs/22-websocket-protocol-reference.md');
  const cliApi = read('docs/23-cli-reference.md');
  const frontendGuide = read('docs/24-frontend-integration-guide.md');
  const capabilityMatrix = read('docs/26-capability-matrix.md');
  const invariants = read('docs/27-architecture-invariants.md');

  assert.match(readme, /REST.*WebSocket/i);
  assert.match(readme, /queue.*worker/i);
  assert.match(readme, /21-rest-api-reference/);
  assert.match(directoryMap, /foundation\/database/);
  assert.match(directoryMap, /foundation\/queue/);
  assert.match(directoryMap, /application\/worker/);
  assert.match(directoryMap, /application\/tasks\/commands/);
  assert.match(directoryMap, /application\/tasks\/lifecycle/);
  assert.match(directoryMap, /application\/tasks\/planning/);
  assert.match(directoryMap, /application\/tasks\/tools/);
  assert.match(directoryMap, /application\/tasks\/control/);
  assert.match(directoryMap, /application\/tasks\/persistence/);
  assert.match(directoryMap, /application\/tasks\/turns/);
  assert.match(directoryMap, /interfaces\/cli/);
  assert.match(directoryMap, /interfaces\/cli\/chat/);
  assert.match(directoryMap, /interfaces\/ws/);
  assert.match(directoryMap, /watch, stream, tail, and status/i);
  assert.match(phaseTwo, /second-phase|phase two/i);
  assert.match(phaseTwo, /interface reference docs/i);
  assert.match(principles, /create-runtime\.ts/i);
  assert.match(principles, /PromptBuilder/i);
  assert.match(runtimeArchitecture, /runtime\.tasks/i);
  assert.match(runtimeArchitecture, /runtime\.platform/i);
  assert.match(runtimeArchitecture, /append-only/i);
  assert.match(runtimeArchitecture, /skill.*manifest/i);
  assert.match(runtimeArchitecture, /topology/i);
  assert.match(runtimeArchitecture, /UnitContract/i);
  assert.match(runtimeArchitecture, /field narrowing/i);
  assert.match(runtimeArchitecture, /memory selector/i);
  assert.match(runtimeArchitecture, /context-policy\.ts/i);
  assert.match(runtimeArchitecture, /context-compression-policy\.ts/i);
  assert.match(runtimeArchitecture, /stage metadata/i);
  assert.match(runtimeArchitecture, /turn-context-assembly/i);
  assert.match(runtimeArchitecture, /turn-provider-execution/i);
  assert.match(runtimeArchitecture, /turn-planner-execution/i);
  assert.match(runtimeArchitecture, /turn-batch-execution/i);
  assert.match(runtimeArchitecture, /turn-consolidation/i);
  assert.match(runtimeArchitecture, /turn-runtime-state-builder/i);
  assert.match(runtimeArchitecture, /turn-result-persistence/i);
  assert.match(runtimeArchitecture, /command-dispatcher/i);
  assert.match(runtimeArchitecture, /successful-turn-persistence/i);
  assert.match(runtimeArchitecture, /provider-batch/i);
  assert.match(runtimeArchitecture, /benchmark harness/i);
  assert.match(runtimeArchitecture, /realistic complex-DAG suite/i);
  assert.match(runtimeArchitecture, /compatibility fallback/i);
  assert.match(runtimeArchitecture, /ExecutionPlan/);
  assert.match(runtimeArchitecture, /TaskPlannerService/);
  assert.match(runtimeArchitecture, /planVersion/);
  assert.match(runtimeArchitecture, /readyStageUnitIds/);
  assert.match(restApi, /\/tasks/);
  assert.match(restApi, /\/queue\/active/);
  assert.match(restApi, /\/platform\/audit\/:resourceType\/:resourceId/);
  assert.match(restApi, /activeSnapshotVersion/);
  assert.match(restApi, /reloadApplied/);
  assert.match(restApi, /restartRequired/);
  assert.match(websocketApi, /ready/);
  assert.match(websocketApi, /runtime_event/);
  assert.match(cliApi, /tasks watch/);
  assert.match(cliApi, /tasks stream/);
  assert.match(cliApi, /tasks chat/);
  assert.match(cliApi, /^### `chat/m);
  assert.match(cliApi, /platform audit <RESOURCE_TYPE> <RESOURCE_ID>/);
  assert.match(capabilityMatrix, /repository-backed summary listing/i);
  assert.match(capabilityMatrix, /append-only command and audit logs/i);
  assert.match(capabilityMatrix, /Explicit topology graph/i);
  assert.match(capabilityMatrix, /Exit-condition-driven completion acceptance/i);
  assert.match(capabilityMatrix, /field narrowing/i);
  assert.match(capabilityMatrix, /Structured memory selector/i);
  assert.match(capabilityMatrix, /Planner-ready stage metadata/i);
  assert.match(capabilityMatrix, /ExecutionPlan/i);
  assert.match(capabilityMatrix, /TaskPlannerService/i);
  assert.match(capabilityMatrix, /provider-batch/i);
  assert.match(capabilityMatrix, /fixed benchmark harness/i);
  assert.match(capabilityMatrix, /realistic benchmark suite/i);
  assert.match(capabilityMatrix, /TOOL_BATCH_PLANNED/i);
  assert.match(capabilityMatrix, /CONSOLIDATION_COMPLETED/i);
  assert.match(capabilityMatrix, /blockingReason/i);
  assert.match(capabilityMatrix, /unsafe batch rejection visibility/i);
  assert.match(capabilityMatrix, /contract source/i);
  assert.match(capabilityMatrix, /task-turn-runner/i);
  assert.match(capabilityMatrix, /27-architecture-invariants/);
  assert.match(invariants, /grouped facade/i);
  assert.match(invariants, /tasks chat/i);
  assert.match(invariants, /workspace chat state remains CLI-local/i);
  assert.match(invariants, /config authority/i);
  assert.match(invariants, /platform command/i);
  assert.match(invariants, /Contract And Topology Boundary/i);
  assert.match(invariants, /field-level narrowing/i);
  assert.match(invariants, /memory selector/i);
  assert.match(invariants, /context-policy\.ts/i);
  assert.match(invariants, /context-compression-policy\.ts/i);
  assert.match(invariants, /Context assembly, provider execution, and persistence/i);
  assert.match(invariants, /focused `application\/tasks\/commands` handlers/i);
  assert.match(invariants, /`application\/tasks\/lifecycle`/i);
  assert.match(invariants, /`application\/tasks\/planning`/i);
  assert.match(invariants, /`application\/tasks\/tools`/i);
  assert.match(invariants, /`application\/tasks\/control`/i);
  assert.match(invariants, /focused `application\/tasks\/persistence` helpers/i);
  assert.match(invariants, /`application\/tasks\/turns`/i);
  assert.match(invariants, /stage semantic validation/i);
  assert.match(invariants, /benchmark-only forced fallback/i);
  assert.match(invariants, /synthetic and realistic benchmark suites/i);
  assert.match(invariants, /compatibility fallback/i);
  assert.match(invariants, /ExecutionPlan/i);
  assert.match(invariants, /TaskPlannerService/i);
  assert.match(invariants, /consolidation is the only stage-level acceptance entry point/i);
  assert.match(frontendGuide, /REST is the fact source/i);
});

test('create-runtime stays a facade and does not absorb turn orchestration details', () => {
  const createRuntimeSource = read('src/application/create-runtime.ts');

  assert.doesNotMatch(createRuntimeSource, /buildTurnPrompt/);
  assert.doesNotMatch(createRuntimeSource, /parseTurn/);
  assert.doesNotMatch(createRuntimeSource, /applyTrackerState/);
  assert.doesNotMatch(createRuntimeSource, /createTopologyGraph/);
  assert.doesNotMatch(createRuntimeSource, /validateTaskDefinitionPreflight/);
  assert.doesNotMatch(createRuntimeSource, /createExecutionPlan/);
  assert.doesNotMatch(createRuntimeSource, /TaskPlannerService/);
  assert.match(createRuntimeSource, /createRuntimeServiceBundle/);
  assert.match(createRuntimeSource, /readonly tasks: BackendNewTasksFacade/);
  assert.match(createRuntimeSource, /readonly platform: BackendNewPlatformFacade/);
  assert.match(createRuntimeSource, /readonly analysis: BackendNewAnalysisFacade/);
  assert.match(createRuntimeSource, /readonly extensions: BackendNewExtensionsFacade/);
  assert.match(createRuntimeSource, /readonly worker: BackendNewWorkerFacade/);
  assert.doesNotMatch(createRuntimeSource, /async submitTask\(/);
  assert.doesNotMatch(createRuntimeSource, /async startTask\(/);
  assert.doesNotMatch(createRuntimeSource, /async analyzeTurn\(/);
  assert.doesNotMatch(createRuntimeSource, /\n\s*readonly taskApplication:/);
  assert.doesNotMatch(createRuntimeSource, /\n\s*readonly platformApplication:/);
  assert.doesNotMatch(createRuntimeSource, /\n\s*readonly taskRepository:/);
  assert.doesNotMatch(createRuntimeSource, /\n\s*readonly providers:/);
  assert.doesNotMatch(createRuntimeSource, /\n\s*readonly platformCommands:/);
});

test('authority and reconcile implementation paths remain explicit in source', () => {
  const createRuntimeSource = read('src/application/create-runtime.ts');
  const configService = read('src/application/platform/config-service.ts');
  const contextPolicy = read('src/domain/runtime/context-policy.ts');
  const contextSelection = read('src/domain/runtime/context-selection.ts');
  const executionPlan = read('src/domain/runtime/execution-plan.ts');
  const promptBuilder = read('src/domain/runtime/prompt-builder.ts');
  const taskTurnRunner = read('src/application/tasks/task-turn-runner.ts');
  const taskPlannerService = read('src/application/tasks/planning/task-planner-service.ts');
  const turnPlannerExecution = read('src/application/tasks/turns/turn-planner-execution.ts');
  const turnBatchExecution = read('src/application/tasks/turns/turn-batch-execution.ts');
  const turnConsolidation = read('src/application/tasks/turns/turn-consolidation.ts');
  const turnContextAssembly = read('src/application/tasks/turns/turn-context-assembly.ts');
  const turnProviderExecution = read('src/application/tasks/turns/turn-provider-execution.ts');
  const turnResultPersistence = read('src/application/tasks/turn-result-persistence.ts');
  const turnRuntimeStateBuilder = read('src/application/tasks/turns/turn-runtime-state-builder.ts');
  const turnOutcomeMapper = read('src/application/tasks/turns/turn-outcome-mapper.ts');
  const tasksIndex = read('src/application/tasks/index.ts');
  const commandDispatcher = read('src/application/tasks/commands/command-dispatcher.ts');
  const lifecycleCommandHandler = read('src/application/tasks/commands/lifecycle-command-handler.ts');
  const successfulTurnPersistence = read('src/application/tasks/persistence/successful-turn-persistence.ts');
  const taskProjectionPersistence = read('src/application/tasks/persistence/task-projection-persistence.ts');
  const stageSemanticValidator = read('src/domain/validation/validate-stage-semantic-contract.ts');
  const runtimeBenchmark = read('src/application/benchmark/runtime-benchmark.ts');
  const skillLoader = read('src/foundation/extensions/skill-loader.ts');
  const platformTypes = read('src/application/platform/types.ts');

  assert.match(configService, /createConfigSnapshotRecord/);
  assert.match(configService, /applyControlledReload/);
  assert.doesNotMatch(configService, /Object\.assign\(this\.foundation\.config/);
  assert.match(skillLoader, /readSkillManifest/);
  assert.match(skillLoader, /writeSkillManifest/);
  assert.match(skillLoader, /replaceSkills/);
  assert.match(skillLoader, /reconciled/);
  assert.match(platformTypes, /PlatformActionResult/);
  assert.match(platformTypes, /ConfigReloadResult/);
  assert.match(contextPolicy, /resolveContextSelection/);
  assert.match(contextPolicy, /usedCompatibilityFallback/);
  assert.match(executionPlan, /ExecutionPlan/);
  assert.match(executionPlan, /validateExecutionPlan/);
  assert.match(taskPlannerService, /createExecutionPlan/);
  assert.match(turnPlannerExecution, /PLAN_CREATED/);
  assert.match(turnPlannerExecution, /PLAN_VALIDATED/);
  assert.match(turnPlannerExecution, /plannedProviderBatches/);
  assert.match(turnBatchExecution, /planAndExecute/);
  assert.match(turnConsolidation, /CONSOLIDATION_STARTED/);
  assert.match(turnConsolidation, /CONSOLIDATION_COMPLETED/);
  assert.match(stageSemanticValidator, /validateStageSemanticContract/);
  assert.match(runtimeBenchmark, /runFixedRuntimeBenchmark/);
  assert.match(runtimeBenchmark, /runRuntimeBenchmarkSuite/);
  assert.match(runtimeBenchmark, /createRealisticBenchmarkDefinitions/);
  assert.match(runtimeBenchmark, /createValidationBenchmarkDefinitions/);
  assert.match(runtimeBenchmark, /benchmark\.forceSingleActiveFallback/);
  assert.match(contextSelection, /selectMemoryForContext/);
  assert.match(contextSelection, /selectValidatedOutputsForContext/);
  assert.doesNotMatch(promptBuilder, /selectMemoryForContext/);
  assert.doesNotMatch(promptBuilder, /resolveContextSelection/);
  assert.doesNotMatch(taskTurnRunner, /memoryKinds/);
  assert.doesNotMatch(taskTurnRunner, /includeGlobalMemory/);
  assert.doesNotMatch(taskTurnRunner, /buildTurnPrompt/);
  assert.doesNotMatch(taskTurnRunner, /buildProviderCompletionRequest/);
  assert.doesNotMatch(taskTurnRunner, /createExecutionPlan/);
  assert.doesNotMatch(taskTurnRunner, /validateExecutionPlan/);
  assert.match(taskTurnRunner, /assembleTurnContext/);
  assert.match(taskTurnRunner, /executeTurnProvider/);
  assert.match(taskTurnRunner, /plannerExecution/);
  assert.match(taskTurnRunner, /batchExecutor/);
  assert.match(taskTurnRunner, /consolidation/);
  assert.match(taskTurnRunner, /buildTurnRuntimeState/);
  assert.match(taskTurnRunner, /mapPlannerStageOutcome/);
  assert.match(taskTurnRunner, /persistSuccessfulTurn/);
  assert.match(turnContextAssembly, /buildTurnPrompt/);
  assert.match(turnProviderExecution, /buildProviderCompletionRequest/);
  assert.match(turnResultPersistence, /SuccessfulTurnPersistence/);
  assert.match(turnRuntimeStateBuilder, /applyTrackerState/);
  assert.match(turnOutcomeMapper, /mapPlannerStageOutcome/);
  assert.match(commandDispatcher, /RESOLVE_APPROVAL/);
  assert.match(lifecycleCommandHandler, /TASK_RESTARTED/);
  assert.match(successfulTurnPersistence, /persistSuccessfulTurnProjection/);
  assert.match(taskProjectionPersistence, /buildTaskProjection/);
  assert.doesNotMatch(tasksIndex, /tool-dispatch-orchestrator/);
  assert.doesNotMatch(createRuntimeSource, /readonly listProviders:/);
  assert.match(read('src/application/platform/platform-mutation-recorder.ts'), /recordCommand/);
  assert.match(read('src/application/platform/platform-mutation-recorder.ts'), /recordApplied/);
});
